config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'users/' => 'welcome#index'
  get '/me' => 'welcome#index'
  get 'signup' => 'users#new'
  get 'users/:id' => 'users#show', as: :user
  get 'users/:id/edit' => 'users#edit', as: :edit_user
  post 'users/' => 'users#create'
  patch 'users/:id' => 'users#update'
  delete 'users/:id/' => 'users#destroy'

  get '/login'     => 'sessions#new'
  post '/login'    => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get 'records/' => 'records#index'
  get 'records/new' => 'records#new', as: :new_record
  get 'records/:id' => 'records#show', as: :record
  get 'records/:id/edit' => 'records#edit', as: :edit_record
  post 'records/' => 'records#create'
  delete 'records/:id/' => 'records#destroy'
  put 'records/:id/' => 'records#patch'
  patch 'records/:id/' => 'records#patch'

  get 'lists/:id' => 'lists#show', as: :list
  patch 'lists/:id/' => 'lists#update'

end

app/models/list.rb
class List < ActiveRecord::Base
	has_and_belongs_to_many :records
	belongs_to :user
end

app/models/record.rb
class Record < ActiveRecord::Base
	mount_uploader :cover, CoverImageUploader
	has_and_belongs_to_many :lists
	has_many :users, through: :lists

	validates :artist, presence: true
	validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :lists
  has_many :records, through: :lists

  attr_reader :password

  def password=(unencrypted_password)
    unless unencrypted_password.empty?
      @password = unencrypted_password
      self.password_digest = BCrypt::Password.create(unencrypted_password)
    end
  end

  def authenticate(unencrypted_password)
    if BCrypt::Password.new(self.password_digest) == unencrypted_password
      return self
      else
      return false
    end
  end

  validates :username, presence: true
  validates :email, presence: true, uniqueness: {case_sensitive: false}, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :password, presence: true, confirmation: true, length: {in: 6..20}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    
  end

  def update
  	@list = List.find(params[:id])
  	@record = Record.find(params[:list][:record_id])
  	@user_stack = current_user.lists.first.records
  	@user_wants = current_user.lists.last.records
  	
  	if @list.name == "have"
	  	unless @user_stack.exists?(@record)
	  		@list.records << @record
	  	else
	  		@list.records.delete(@record)
	  	end
	elsif @list.name == "want"
		unless @user_wants.exists?(@record)
			@list.records << @record
		else
			@list.records.delete(@record)
		end
	end

  	
  	if @list.save
  		redirect_to record_path(@record)
  	end
  end

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  
	def index
		@records = Record.all
	end

	def show
		@record = Record.find(params[:id])
		@users = @record.users.all
    @user_stack = current_user.lists.first
    @user_wants = current_user.lists.last
    @users_have = @record.lists.where(name:"have")
	end

	def new 
		@record = Record.new
	end

  def create
    @record = Record.new(record_params)
    if @record.save
      redirect_to record_path(@record)
    else
      render :new
    end
  end

  def edit
    @record = Record.find(params[:id])
  end

  def patch
    @record = Record.find(params[:id])
    @record.update_attributes(record_params)
    redirect_to record_path(@record)
  end

  def destroy
    @record = Record.find(params[:id])
    @record.destroy
    redirect_to records_path
  end


	private
	def record_params
		params.require(:record).permit(:artist,:title,:cover)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end


  def create
    user = User.find_by(email: params[:login][:email])
    if user && user.authenticate(params[:login][:password])
      session[:user_id] = user.id.to_s
      redirect_to user_path(user)
    else
      redirect_to login_path
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		@have_list = List.create(name:"have")
		@want_list = List.create(name:"want")
		@user.lists << @have_list
		@user.lists << @want_list
		if @user.save
			session[:user_id] = @user.id.to_s
			redirect_to user_path(@user)
		else
			render :new
		end
	end

	def show
		@user = User.find(params[:id])
		@user_stack = @user.lists.first.records.all
		@user_wants = @user.lists.last.records.all
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
	  @user = User.find(params[:id])

	  if @user.update(user_params)
	    flash[:message] = "User profile successfully updated!"
	    redirect_to users_path
	  else
	    render :edit
	  end
	end

	def destroy
	  @user = User.find(params[:id])
		@user_lists = List.where(user_id:@user.id)
	  @user_lists.destroy_all
	  @user.destroy
	  session.delete(:user_id)
    redirect_to root_path
	end



	private
	def user_params
		params.require(:user).permit(:username, :email, :first_name, :last_name, :password, :password_confirmation)
	end
	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  


  def index
    if logged_in?
    	redirect_to user_path(current_user)
    end
  end

  private 
  def logged_in?
    session[:user_id] != nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def logged_in?
	  session[:user_id] != nil
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StacksTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render "shared/header" %>

	<div id="container">
		<%= yield %>
	</div><!-- container -->

	<%= render "shared/footer" %>

	<link href='https://fonts.googleapis.com/css?family=Lato:300,400,700,400italic,700italic' rel='stylesheet' type='text/css'>
	<link href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
</body>
</html>

app/views/records/_buttons.html.erb
<% unless current_user.lists.first.records.exists?(@record) %>

  <%= form_for @user_stack do |f| %>
      <%= f.hidden_field :record_id, value: @record.id %>
      <%= f.submit "+ Add to Stack", class: 'btn' %>
  <% end %>

<% else %>

  <%= form_for @user_stack do |f| %>
    <h3><%= @record.title %> is in your Stack</h3>
    <%= f.hidden_field :record_id, value: @record.id %>
    <%= f.submit "- Remove from Stack", class: 'btn' %>
  <% end %>

 <% end %>


<% unless current_user.lists.last.records.exists?(@record) %>

  <%= form_for @user_wants do |f| %>
    <%= f.hidden_field :record_id, value: @record.id %>
    <%= f.submit "+ Add to Wantlist", class: 'btn' %>
  <% end %>

<% else %>

  <%= form_for @user_wants do |f| %>
    <h3><%= @record.title %> is in your Wantlist</h3>
    <%= f.hidden_field :record_id, value: @record.id %>
    <%= f.submit "- Remove From Wantlist", class: 'btn' %>
  <% end %>

<% end %>


<ul id="other-stacks">
  <h3>Other owners:</h3>
  <% @users_have.each do |user| %>
    <li><%= link_to user.user.username, user_path(user) unless current_user == user %></li>
  <% end %>
</ul>

app/views/records/_form.html.erb
<%= form_for @record do |f| %>
  <%= f.text_field :artist, placeholder: "Artist Name" %>
  <%= f.text_field :title, placeholder: "Album Title" %>
  <%= f.file_field :cover, value:"upload" %>
  <%= f.submit "submit" %>
<% end %>

app/views/records/edit.html.erb
<div id="edit-record-container" class="form-page">
	
	<h1>Edit Record</h1>

	<%= render 'form' %>

	<%= link_to 'delete', @record, method: :delete %>

</div>

app/views/records/index.html.erb
<div id="add-search">
	
	<%= link_to "+ Add a Record", new_record_path, class:'btn add' %>
</div><!-- add-search -->

<div id="records-container">
	<ul>
	<% @records.each do |record| %>

		<li>
		    <div class="cover"><%= link_to image_tag(record.cover_url, size: '300x300'), record_path(record) if record.cover?  %></div>
		    <div class="info">
		        <div class="meta">    
		            <p class="artist"><%= link_to record.artist, record_path(record) %></p>
		            <p class="title"><%= record.title %></p>
		        </div>
		    </div><!--info -->
		</li>
	<% end %>
	</ul>
</div>

app/views/records/new.html.erb
<div id="add-record-container" class="form-page">

	<h1>Add Record</h1>

	<%= render 'form' %>

</div><!-- end add-record-container -->

app/views/records/show.html.erb
<div id="record-container">
    <div id="record-data">

        <div id="record-left">
            <div class="cover"><%= link_to image_tag(@record.cover_url, size: '300x300'), edit_record_path(@record) if @record.cover? %></div>
           
        </div>
        <div id="record-right">
            <h2><%= @record.artist %></h2>
            <h3><%= @record.title %></h3>
            <p>Elektra Records</p>
            <ol>
                <li>In Between Days</li>
                <li>Kyoto Song</li>
                <li>The Blood</li>
                <li>Six Different Ways</li>
                <li>Push</li>
                <li>The Baby Screams</li>
                <li>Close to Me</li>
                <li>A Night Like This</li>
                <li>Screw</li>
                <li>Sinking</li>
            </ol>
        </div>
    </div><!-- record data -->
    <div id="notes">

        <%= render 'buttons' %>

     
    </div>
</div><!-- record container -->

app/views/shared/_footer.html.erb
<footer>
	<div class="wrapper">
		<div class="top">
			<h2 class="logo"><i class="fa fa-align-left fa-rotate-270"></i>stacks</h2>
		</div><!-- top -->
		<div class="bottom">
			<ul>
				<li>
					<% if logged_in? %>
					  <%= render 'shared/nav' %>
					<% else %>
					  <%= link_to 'Log In', login_path %>
					  <li><%= link_to "Signup", signup_path %></li>
					<% end %>
				</li>
				
			</ul>
		</div><!-- bottom -->
	</div><!-- wrapper -->
</footer>

app/views/shared/_header.html.erb
<header>
	<div class="wrapper">
	    <h1 class="logo"><i class="fa fa-align-left fa-rotate-270"></i><%= link_to "stacks", root_path %></h1>
	    <div id="entry-point">
	    	<% if logged_in? %>
	    		<%= render 'shared/nav' %>
        	<% else %>
        		<%= link_to "Log In", login_path, class:'btn' %>
	        	<%= link_to "Signup", signup_path, class:'btn' %>
        	<% end %>
	    </div>
    </div><!-- wrapper -->
</header>

app/views/shared/_nav.html.erb
<nav>
	<ul>
    	<li><%= link_to "My Stack", user_path(current_user) %></li>
    	<li><%= link_to "Browse", records_path %></li>
    	<li><%= link_to "Add Record", new_record_path %></li>
    	<li><%= link_to 'Log Out', logout_path, method: :delete %></li>
	</ul>
</nav>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  
  <div>
    <%= f.text_field :username, placeholder: "Username" %>
    <%= f.text_field :email, placeholder: "Email Address" %>
  </div>

  <div>
    <%= f.text_field :first_name, placeholder: "First Name" %>
    <%= f.text_field :last_name, placeholder: "Last Name" %>
  </div>

  <div>
    <%= f.password_field :password, placeholder:"Password" %>
    <%= f.password_field :password_confirmation, placeholder:"Confirm Password" %>
  </div>

  <%= f.submit "submit"%>

<% end %>

app/views/users/edit.html.erb
<div id="signup-container">


	<% if @user.errors.any? %>
	  <div>
	    <h4><%= pluralize(@user.errors.count, "error") %> prevented you from signing up.</h4>
	    <ul>
	      <% @user.errors.full_messages.each do |msg| %>
	      <li><%= msg.downcase %></li>
	      <% end %>
	    </ul>
	    </div>
	<% end %>

	<%= render 'form' %>

	<%= link_to "Delete Your Account", @user, method: :delete %>
		


</div>

app/views/users/new.html.erb
<div id="signup-container">

	<div>
		<h1>Create an Account</h1>
		<p>Join the best vinyl community</p>
	</div>

	<div>
		<a href="#">Sign in with <i class="fa fa-spotify"></i> Spotify</a><br>
		<span>-or-</span>
	</div>

	<% if @user.errors.any? %>
	  <div>
	    <h4><%= pluralize(@user.errors.count, "error") %> prevented you from signing up.</h4>
	    <ul>
	      <% @user.errors.full_messages.each do |msg| %>
	      <li><%= msg.downcase %></li>
	      <% end %>
	    </ul>
	    </div>
	<% end %>

	<%= render 'form' %>
		


</div>

app/views/users/show.html.erb
<div id="profile-container">

	<div id="user-menu">
		<% if current_user == @user  %><%= link_to "edit profile", edit_user_path(@user) %><% end %>
	</div>

	<section id="my-stack" class="record-list">
		
		<% if current_user == @user  %>
			<h2>My Stack</h2>
		<% else %>
			<h2><%= @user.first_name %>'s Stack</h2>
		<% end %>

		
		<% unless @user_stack.count == 0 %>
			<ul>
			<% @user_stack.each do |record| %>
			    <li>
			        <div class="cover"><%= link_to image_tag(record.cover_url, size: '300x300'), record_path(record) if record.cover?  %></div>
			        <div class="info">
			            <div class="meta">    
			                <p class="artist"><%= link_to record.artist, record_path(record) %></p>
			                <p class="title"><%= record.title %></p>
			            </div>
			        </div><!--info -->
			    </li>
			<% end %>
			</ul><!-- full-list -->
		<% else %>
			<ul><li>Nothing here... <%= link_to "Browse", records_path %> or <%= link_to "Add a new Record", new_record_path %></li></ul>
		<% end %>
	</section><!-- my_stack -->


	<section id="my-list" class="record-list">
		<% if current_user == @user  %>
			<h2>My Wantlist</h2>
		<% else %>
			<h2><%= @user.first_name %>'s Wantlist</h2>
		<% end %>
		<% unless @user_wants.count == 0 %>
			<ul>
			<% @user_wants.each do |record| %>
			    <li>
			        <div class="cover"><%= link_to image_tag(record.cover_url, size: '300x300'), record_path(record) if record.cover?  %></div>
			        <div class="info">
			            <div class="meta">    
			                <p class="artist"><%= link_to record.artist, record_path(record) %></p>
			                <p class="title"><%= record.title %></p>
			            </div>
			        </div><!--info -->
			    </li>
			<% end %>
			</ul><!-- full-list -->
		<% else %>
			<ul><li>Nothing here... <%= link_to "Browse", records_path %> or <%= link_to "Add a new Record", new_record_path %></li></ul>
		<% end %>
	</section><!-- my_wants -->

</div><!-- profile-container -->

app/views/welcome/index.html.erb
<div id="welcome-container">
<div id="video"><%= video_tag 'http://ga.kyleconkright.com/assets/video.m4v', autoplay:'true', loop: 'true', width: '100%' %></div><!-- video -->
    <div id="welcome">
        <h1>Welcome to Stacks</h1>
        <p>A place to organize, obsess, catalog, discuss, and listen to your vinyl collection.</p>
        <div id="buttons">
            <%= link_to "Log In", login_path, class: 'btn' %>
            <%= link_to "Signup", signup_path, class:'btn' %>
            <span>-or-</span>
            <a class="btn spotify" href="#">Sign in with <i class="fa fa-spotify"></i> Spotify</a>
        </div>
    </div><!-- Welcome Div -->
</div><!-- welcome container -->